sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
before_install: gem install bundler -v 1.16.2

matrix:
  allow_failures:
    - rvm: ruby-head
