#!/usr/bin/env ruby
# frozen_string_literal: true

require 'vanishing_vision'
require 'vanishing_vision/version'
require 'optparse'

Version = VanishingVision::VERSION

options = {}

opt = OptionParser.new('usage: vanish [-a] [path ...]')
opt.on('-a', '--auto-correct', 'auto correct (default is just to display)') {|v| options[:auto_correct] = true }
opt.on('-v', '--version', 'version') {|v| options[:version] = true } # overwrite

begin
  opt.permute!(ARGV)

  if options[:version]
    puts "vanish #{VanishingVision::VERSION}"
    exit
  end

  paths = ARGV.empty? ? ['.'] : ARGV

  paths.each do |path|
    VanishingVision.vanish(path, options)
  end
rescue
  puts opt.help

  exit!
end
